version: '3.7'
services:
  eventhos-api:
    build: .
    container_name: eventhos-api
    ports:
      - '2109:2109'
    environment:
      NODE_ENV: "production"
      CPU_COUNT: 1
      PORT: 2109      
      DATA_BASE_NAME: "eventhos"
      DATA_BASE_HOST: host.docker.internal
      DATA_BASE_PORT: 3306
      DATA_BASE_USER: "usr_eventhos"
      DATA_BASE_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      DATA_BASE_POOL_MAX: 300
      DATA_BASE_POOL_MIN: 100
      DATA_BASE_ACQUIRE_CONNECTION_TIMEOUT: 10000
      JWT_SECRET: ${JWT_SECRET:-changeme}
      CRYPTO_KEY: ${CRYPTO_KEY:-changeme}
      SMTP_HOST: ${SMTP_HOST:-changeme}
      SMTP_PORT: ${SMTP_PORT:-changeme}
      SMTP_CREDENTIAL_USER: ${SMTP_CREDENTIAL_USER:-changeme}
      SMTP_CREDENTIAL_PASSWORD: ${SMTP_CREDENTIAL_PASSWORD:-changeme}
      SMTP_ENABLE_SSL: "true"
      SMTP_TLS_CIPHERS: SSLv3
      SMTP_DEFAULT_RECIPIENT: ${SMTP_DEFAULT_RECIPIENT:-changeme}
      TZ: America/Lima
    depends_on:
      eventhos-db:
        condition: service_healthy
    networks:
      - app_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      resources:
        limits:
          memory: 1024M
  eventhos-db:
    image: mysql:5.7
    command: mysqld --sql_mode="" --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    container_name: eventhos-db
    ports:
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_USER: 'usr_eventhos'
      MYSQL_DATABASE: 'eventhos'
      TZ: America/Lima
    deploy:
      resources:
        limits:
          memory: 1024M
    healthcheck:
      test: 'cat /var/log/mysql/general-log.log | grep "root@localhost on  using Socket"'
      interval: 10s
      retries: 120

networks:
  app_network:
    driver: bridge
